/**
 * state.js
 * Global application state shared across all modules.
 */

let states       = [];   // Array of state name strings, e.g. ['q0', 'q1']
let transitions  = [];   // Array of {from, symbol, to} objects
let startState   = '';   // Name of the start state
let acceptStates = [];   // Array of accept state names
let steps        = [];   // Derivation steps generated by Arden's engine
let currentStep  = 0;    // Index of the currently displayed step
let cyInstance   = null; // Cytoscape graph instance
